version: '3.8'
services:
  app:
    build:
      context: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/testtraffic
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    container_name: test-traffic-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testtraffic
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
